# see https://docs.helix-editor.com/editor.html

theme = "base16_transparent"

[editor]
auto-format = false
popup-border = "all"

[editor.statusline]
center = ["version-control"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true
