syntax enable

set number  " lines number
set ruler   " cursor position

set expandtab      " Expand TAB to spaces
set tabstop=4      " Number of visual spaces per TAB
set softtabstop=4  " Number of spaces in tab when editing
set shiftwidth=4   " Number of spaces to use for autoindent

set viminfofile=NONE

let &t_EI = "\<Esc>[2 q"  " normal  - block
let &t_SI = "\<Esc>[6 q"  " insert  - bar
let &t_SR = "\<Esc>[4 q"  " replace - underline
